# Generated by Django 5.1 on 2024-08-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expiration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
